### ISSUE TITLE
Cipher Error

### ISSUE THREAD

**Issue by Xeonzinc** [dickydoouk/tp-link-tapo-connect#1]
Hi, this library looks great, I've been looking for a node js P100 implementation for a while. I can login to the cloud just fine, and get a list of all my devices, however both loginDevice & loginDeviceByIp functions to get a device token return the following error:

```javascript
(node:7152) UnhandledPromiseRejectionWarning: TypeError: Passphrase required for encrypted key
    at Object.privateDecrypt (internal/crypto/cipher.js:63:12)
    at Object.readDeviceKey (C:\..\node_modules\tp-link-tapo-connect\dist\tplinkCipher.js:82:38)
    at C:\..\node_modules\tp-link-tapo-connect\dist\api.js:143:44
    at step (C:\..\node_modules\tp-link-tapo-connect\dist\api.js:44:23)
    at Object.next (C:\..\node_modules\tp-link-tapo-connect\dist\api.js:25:53)
    at fulfilled (C:\..\node_modules\tp-link-tapo-connect\dist\api.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:7152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea what may be causing this? My implementation is essentially the same as the examples on the readme?

```javascript
var tapo = require('tp-link-tapo-connect');

async function getDevices() {
	
const cloudToken = await tapo.cloudLogin("email@domain.com", "pass");  
const devices = await tapo.listDevicesByType(cloudToken, 'SMART.TAPOPLUG');
console.log(cloudToken);
console.log(devices);

const deviceToken = await tapo.loginDevice("email@domain.com", "pass",devices[5]);
console.log(deviceToken);   

//const deviceToken = await tapo.loginDeviceByIp("email@domain.com", "pass", "192.168.0.185");
//console.log(deviceToken);   

const getDeviceInfoResponse = await tapo.getDeviceInfo(deviceToken);
console.log(getDeviceInfoResponse);

await tapo.turnOn(deviceToken);

}
getDevices();
```

**Comment by lucxoff** [comment]
Same issue, both of method, my code : 

`var tpLinkTapoConnect = require("tp-link-tapo-connect")
 
const TPLINK_USER = "email@test.com";
const TPLINK_PASS = "password";
const find = require('local-devices');
async function main() {
  
    const cloudToken = await tpLinkTapoConnect.cloudLogin(TPLINK_USER, TPLINK_PASS);
    const devices = await tpLinkTapoConnect.listDevicesByType(cloudToken, 'SMART.TAPOPLUG');

    console.log(devices[0]);

    
    
    // Find all local network devices.
    find().then(devicesip => {
    console.log(devicesip) 
    })

    const deviceToken = await tpLinkTapoConnect.loginDeviceByIp(TPLINK_USER, TPLINK_PASS, "192.168.8.105");
    
    const getDeviceInfoResponse = await tpLinkTapoConnect.getDeviceInfo(deviceToken);
    console.log(getDeviceInfoResponse);

    await turnOff(deviceToken);

}
 
main();`

**Comment by lucxoff** [comment]
@Xeonzinc Ok, i have the solution, it's about passing passphrase when generate key. 

So i just add to module a new param : ``passphrase: "top secret"`` when readDeviceKey is call. And for request who generate key Pair i pass a param passphrase too.

PS: I'm gonna make a pull request after
