### ISSUE TITLE
L530E Preset colors

### ISSUE THREAD

**Issue by Zhurkk** [dickydoouk/tp-link-tapo-connect#11]
Hello,

I am currently using this library with node red to control my bulbs at home.
I have 1 issue tough. Whenever a change the color of the L530E I cannot change it back to warm white 2700K.
I have tried playing around with the color codes. 
It would be wonderful if you could add a new preset color for the warm white with 2700 Kelvin 🙏

Thank you 
Zhurk

**Comment by dickydoouk** [comment]
@dewhurstwill would you be able to have a look at this as I have no way of testing this as I don't possess a L530E

**Comment by dewhurstwill** [comment]
PR Raised with  a fix ^
