### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Triyono123** [dickydoouk/tp-link-tapo-connect#14]
Is there any way we could send timer command to the device? for example like, we want the device to be ON 5 minutes from now, and then OFF 10 minutes from now.
Please advice.

**Comment by dewhurstwill** [comment]
I will look at adding this functionality to the library

**Comment by dewhurstwill** [comment]
Feature PR added - Pending review

@dickydoouk

**Comment by dickydoouk** [comment]
@Triyono123 This can be done currently yourself wrapping the turnOn call or turnOff call in a setTimeout call e.g.

`setTimeout(() => turnOn(), 5000)`

**Comment by dickydoouk** [comment]
In the future I am hoping we can reverse engineer the scheduling api the smart plug uses the way the official Tapo app sets timers and schedules.
