### ISSUE TITLE
Accessing color luminosity

### ISSUE THREAD

**Issue by fredmorais** [dickydoouk/tp-link-tapo-connect#15]
Hello there. So the 530 lamps can either work in two modes: RGB or white. I am working in RGB so let's forget about the white part. If I set any RGB color through the setColour function it works great. However, if I then run getDeviceInfo it returns the current color in HSL instead of RGB, which is fine (just a conversion). The problem is that it only returns the Hue and Saturation values, leaving Luminosity out. Without it I can not convert the color to RGB. I don't know if this is a problem of the lamp itself or if it is something changeable in the library's code. Could you please help me in this issue?

I have an hint on what might be, but I might be wrong. If the lamp is "running" an RGB color and you call getDeviceInfo you get a color_temp value, which is only for when the color is "running" a white color. Maybe the library is returning this value by mistake instead of the luminosity.

Any help is appreciated. Thank you in advance.

**Comment by dewhurstwill** [comment]
I will take a look into this

**Comment by dewhurstwill** [comment]
From what I can tell, the brightness level is the luminosity in terms of what is returned. Or at least that is what we use for the conversion from #hex to HSL. 

Hope this helps

**Comment by fredmorais** [comment]
Hello again. Firstly, I reached a conclusion and will post here for other people, but the brightness level is not the luminosity in HSL. I do not understand the theoretical part 100% and now I don't have time to do the research, I'll just post the method that is working for me.

So, first thing I was doing wrong was thinking the returned value from getDeviceInfo was in HSL format when instead it is in HSV. I mistakenly assumed they were the same (since they both had Hue and Saturation parameters). If you need to find the RGB color of the lamp (assuming it is in RGB mode) you need to convert from HSV to RGB (tons of websites and plugins to do it). The hue and saturation are pretty straight forward, but then you don't have a "value" in your response. What you will do is set it to 100%. I tested this with multiple colors and it returned the right result, so this fixes my problem. The brightness value in the response is not related to the color itself, but rather how bright the lamp is (like the brightness on your devices' screens).

I'm sure that with a bit of color theory the answer will be clear on why the 100% value works.

Hope this helps anyone who was struggling, like me, and thanks @dewhurstwill for your time too!
