### ISSUE TITLE
Support for P110

### ISSUE THREAD

**Issue by johnkazer** [dickydoouk/tp-link-tapo-connect#20]
I haven't investigated yet, but would it be straightforward to add the P110 too?
Maybe these will help
https://github.com/petretiandrea/home-assistant-tapo-p100/issues/64
https://github.com/fishbigger/TapoP100 (python but hopefully translatable)

**Comment by johnkazer** [comment]
I just tried it with my P110 plug and the status node worked fine - returned all correct data. I'll investigate when get the change what other API calls can be used - it'd be great to have access to the electricity use data.

**Comment by NickEarle37** [comment]
Hi, has anyone had success adding the P110, I'd love to be able to access the Energy Monitoring stats.

**Comment by joside** [comment]
I am able to use a P110 but without the Energy Usage Data. There is a https://github.com/dickydoouk/tp-link-tapo-connect/pull/21 which would be nice to be merged soon.

**Comment by dickydoouk** [comment]
Closing this issue as it will be resolved by #21
