### ISSUE TITLE
Getting  -1501: throw new Error("Invalid request or credentials") when trying to execute functions loginDevice or loginDeviceByIp

### ISSUE THREAD

**Issue by icehazard** [dickydoouk/tp-link-tapo-connect#30]

**Comment by khandieyea** [comment]
Same here :/ Maybe tapo firmware updates have changed something. If anyone who successfully has this working could share their firmware version, that'd be great :)

**Comment by dickydoouk** [comment]
I have tested on P100 firmware version: 1.4.9 Build 20210621 Rel. 30941 and all OK
My plugs are refusing to update firmware using the Tapo app at this time but hopefully this info will help.

**Comment by dickydoouk** [comment]
I have now managed to test using latest firmware: 1.4.16 Build 20230224 Rel. 59299 and all OK. This firmware now supports auto off feature.

**Comment by dickydoouk** [comment]
Note the error i get when my cloud email address or password is wrong is -20601. However if there is a mismatch between the cloud credentials and the device I get -1501 (Note: Changing password does not update the smart device credentials, try using older credentials)
