### ISSUE TITLE
Getting -1012: "Unexpected Error Code: -1012 (undefined)" when trying to execute functions turnOn.

### ISSUE THREAD

**Issue by sanlike0911** [dickydoouk/tp-link-tapo-connect#31]
Hi.
I'm using your awesome "dickydoouk/tp-link-tapo-connect".
After updating the firmware of the tapo device, tp-link-tapo-connect returned an error (-1012).
I checked other programs to investigate this issue.
It looks like you need "requestTimeMils and terminalUUID" in the tapo device set_device_info request.
I know you're busy, but I'm looking forward to working with you

[ERROR(-1012)]
https://github.com/dickydoouk/tp-link-tapo-connect/blob/397853f21ca78d05f18ff5ae0d58b5f2dd1b05e9/src/api.ts#L125-L133

[SUCCESS]
I added "equestTimeMils and terminalUUID" to turnDeviceOnRequest .
```
export const turnOn = async (deviceKey: TapoDeviceKey, deviceOn: boolean = true) => {
  const turnDeviceOnRequest = {
    "method": "set_device_info",
    "params":{
      "device_on": deviceOn,
    },
    "requestTimeMils": (new Date()).getTime(),  /* add: sanlike0911 */
    "terminalUUID": "00-00-00-00-00-00"         /* add: sanlike0911 */
  }
  await securePassthrough(turnDeviceOnRequest, deviceKey)
}
```

sanlike0911
https://github.com/sanlike0911/node-red-contrib-tplink-tapo-connect-api

**Comment by dickydoouk** [comment]
I think this has been fixed in https://github.com/dickydoouk/tp-link-tapo-connect/pull/29/ please re-open if not the case

**Comment by dickydoouk** [comment]
Ah! That may have only fixed it for login not for this case. Apologies if so. Please contribute a PR if you have something working.
