### ISSUE TITLE
Update local-devices to 4.0.0 / update NPM build

### ISSUE THREAD

**Issue by ercksen** [dickydoouk/tp-link-tapo-connect#39]
When installing the library you will get 3 high security vulnerabilities due to local-devices still being on 3.2.0
(package.json: `"local-devices": "^3.2.0"`). Although the package.json inside this repository is already on ^4.0.0. Have you forgot publishing the build to npm?

PS: You have not bumped version numbers between the updated package.json files. This will probably cause problems when releasing.

**Comment by dickydoouk** [comment]
This should now be resolved in the latest version 2 of the library and this has been published to NPM.
