### ISSUE TITLE
Not getting the IP address or Status when I do a listDevicesByType

### ISSUE THREAD

**Issue by bigandy** [dickydoouk/tp-link-tapo-connect#4]
Is there any way of getting the IP address or status when I run a listDevicesByType?

I get this back: 

![Screenshot 2021-02-15 at 08 30 53](https://user-images.githubusercontent.com/603328/107922754-66635580-6f68-11eb-87b5-6b22f1e1347b.png)

**Comment by dickydoouk** [comment]
Annoyingly the local ip address is not returned by the cloud methods listDevices/listDevicesByType. Although there is a loginDevice function which converts the deviceMac to local ip using the local-devices library.

```ts
const devices = await listDevicesByType(cloudToken, 'SMART.TAPOPLUG');
    
    const smartPlug = devices[0];

    const deviceToken = await loginDevice(email, password, smartPlug);
    const getDeviceInfoResponse = await getDeviceInfo(deviceToken);
    console.log(getDeviceInfoResponse);
```

This uses a function within the code base called `resolveMacToIp` in `network-tools.ts`

Hope that gives you what you are looking for.

**Comment by dickydoouk** [comment]
Have added some extra documentation to the README to document this functionality

**Comment by bigandy** [comment]
@dickydoouk thanks for this it is just what I needed.
