### ISSUE TITLE
Kasa KP105, HS110, KP115 support?

### ISSUE THREAD

**Issue by dpslwk** [dickydoouk/tp-link-tapo-connect#45]
Any chance of adding support or documenting how to use with Kasa plug devices, 

They show up as `deviceType: 'IOT.SMARTPLUGSWITCH',` rather than `deviceType: 'SMART.TAPOPLUG',`

**Comment by dickydoouk** [comment]
For that you may want to consider my other project https://github.com/dickydoouk/tp-link-kasa-connect
