### ISSUE TITLE
Support for Light bulb L530E?

### ISSUE THREAD

**Issue by SrZorro** [dickydoouk/tp-link-tapo-connect#6]
There is any plans about implementing the L530E? I have that light bulb, If I could have some pointers about the API and whatnot I could try to do a pull request for it.

**Comment by dickydoouk** [comment]
I don't have that light bulb but I would image on/off/dim functionality should work. Not sure about colour/hue setting as I am unclear the property name. Can you confirm if the API can turn the bulb on/off. You can use the api.test.js file and put your credentials in at the top and rename one of the **xtest** functions to **test** then run `npm test`. Would be useful if you could paste here the result of the getDeviceInfo result. Thanks

**Comment by SrZorro** [comment]
Perfect, tomorrow I will do that and come back with the results 👍

**Comment by SrZorro** [comment]
Perfect, all methods are working.

## getDeviceInfo

```json
{
   "device_id":"<device id>",
   "fw_ver":"1.1.8 Build 20201210 Rel. 55943",
   "hw_ver":"1.0.0",
   "type":"SMART.TAPOBULB",
   "model":"L530 Series",
   "mac":"<mac addres>",
   "hw_id":"<hw_id>",
   "fw_id":"<fw_id>",
   "oem_id":"<oem_id>",
   "specs":"EU",
   "lang":"es_ES",
   "device_on":true,
   "on_time":711,
   "overheated":false,
   "nickname":"bedroom",
   "avatar":"floor_lamp_1",
   "brightness":10,
   "dynamic_light_effect_enable":false,
   "color_temp":6000,
   "default_states":{
      "type":"last_states",
      "state":{
         "brightness":10,
         "color_temp":6000
      }
   },
   "time_diff":60,
   "region":"Europe/Madrid",
   "longitude":"<longitude int>",
   "latitude":"<latitude int>",
   "has_set_location_info":true,
   "ip":"<local id>",
   "ssid":"<ssid>",
   "signal_level":3,
   "rssi":-37
}```

**Comment by dickydoouk** [comment]
Thats excellent, thanks for doing that. I'm glad it works. 

Looks like the property name for the colour is `color_temp` so will leave this ticket open till we add that property.

**Comment by SrZorro** [comment]
There should be more properties, I will change the settings from the app and document all the actions, because I don't see an option for the hsl value

**Comment by dewhurstwill** [comment]
I have written a helper, feel free to review and merge.
PR #7

**Comment by dickydoouk** [comment]
Closing this issue as PR working
